name: build-test-deploy
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run tests
        working-directory: ./frontend
        run: |
           yarn install
           yarn run dev
    
